import { ShieldCheck } from "lucide-react";

export function ResponsibleAIDisclaimer({ compact = false }: { compact?: boolean }) {
  if (compact) {
    return (
      <p className="text-xs leading-relaxed text-muted-foreground">
        AI-generated content may be inaccurate. Review before use.
      </p>
    );
  }
  return (
    <div className="flex items-start gap-3 rounded-xl border border-info bg-info/60 p-4">
      <ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-info-foreground" />
      <div>
        <p className="text-sm font-semibold text-info-foreground">Responsible AI</p>
        <p className="mt-1 text-sm leading-relaxed text-info-foreground/90">
          Outputs on this page are generated by AI and may contain inaccuracies, omissions, or
          bias. Always review and verify content before sending, publishing, or acting on it.
          Do not enter confidential, personal, or sensitive data. You remain responsible for
          how AI-generated content is used.
        </p>
      </div>
    </div>
  );
}
