/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiChatRouteImport } from './routes/ai-chat'
import { Route as EmailWriterRouteImport } from './routes/email-writer'
import { Route as MeetingSummarizerRouteImport } from './routes/meeting-summarizer'
import { Route as ResearchAssistantRouteImport } from './routes/research-assistant'
import { Route as TaskPlannerRouteImport } from './routes/task-planner'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiChatRoute = AiChatRouteImport.update({
  id: '/ai-chat',
  path: '/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailWriterRoute = EmailWriterRouteImport.update({
  id: '/email-writer',
  path: '/email-writer',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingSummarizerRoute = MeetingSummarizerRouteImport.update({
  id: '/meeting-summarizer',
  path: '/meeting-summarizer',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchAssistantRoute = ResearchAssistantRouteImport.update({
  id: '/research-assistant',
  path: '/research-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskPlannerRoute = TaskPlannerRouteImport.update({
  id: '/task-planner',
  path: '/task-planner',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-chat': typeof AiChatRoute
  '/email-writer': typeof EmailWriterRoute
  '/meeting-summarizer': typeof MeetingSummarizerRoute
  '/research-assistant': typeof ResearchAssistantRoute
  '/task-planner': typeof TaskPlannerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-chat': typeof AiChatRoute
  '/email-writer': typeof EmailWriterRoute
  '/meeting-summarizer': typeof MeetingSummarizerRoute
  '/research-assistant': typeof ResearchAssistantRoute
  '/task-planner': typeof TaskPlannerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-chat': typeof AiChatRoute
  '/email-writer': typeof EmailWriterRoute
  '/meeting-summarizer': typeof MeetingSummarizerRoute
  '/research-assistant': typeof ResearchAssistantRoute
  '/task-planner': typeof TaskPlannerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-chat'
    | '/email-writer'
    | '/meeting-summarizer'
    | '/research-assistant'
    | '/task-planner'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-chat'
    | '/email-writer'
    | '/meeting-summarizer'
    | '/research-assistant'
    | '/task-planner'
  id:
    | '__root__'
    | '/'
    | '/ai-chat'
    | '/email-writer'
    | '/meeting-summarizer'
    | '/research-assistant'
    | '/task-planner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiChatRoute: typeof AiChatRoute
  EmailWriterRoute: typeof EmailWriterRoute
  MeetingSummarizerRoute: typeof MeetingSummarizerRoute
  ResearchAssistantRoute: typeof ResearchAssistantRoute
  TaskPlannerRoute: typeof TaskPlannerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-chat': {
      id: '/ai-chat'
      path: '/ai-chat'
      fullPath: '/ai-chat'
      preLoaderRoute: typeof AiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-writer': {
      id: '/email-writer'
      path: '/email-writer'
      fullPath: '/email-writer'
      preLoaderRoute: typeof EmailWriterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting-summarizer': {
      id: '/meeting-summarizer'
      path: '/meeting-summarizer'
      fullPath: '/meeting-summarizer'
      preLoaderRoute: typeof MeetingSummarizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-assistant': {
      id: '/research-assistant'
      path: '/research-assistant'
      fullPath: '/research-assistant'
      preLoaderRoute: typeof ResearchAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task-planner': {
      id: '/task-planner'
      path: '/task-planner'
      fullPath: '/task-planner'
      preLoaderRoute: typeof TaskPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiChatRoute: AiChatRoute,
  EmailWriterRoute: EmailWriterRoute,
  MeetingSummarizerRoute: MeetingSummarizerRoute,
  ResearchAssistantRoute: ResearchAssistantRoute,
  TaskPlannerRoute: TaskPlannerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
